version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
